name: Update 3D contribution graph

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Generate sakura contribution graph
        uses: yoshi389111/github-profile-3d-contrib@7d95e7d4cdc028dd1e1cbd957d65f35efb12ae39 # v0.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: ./assets/sakura-3d-settings.json

      - name: Commit generated graph
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile-3d-contrib/sakura-profile.svg
          if git commit -m "chore: update 3D contribution graph"; then
            git push
          fi
